---
- name: Instalar MariaDB Server
  ansible.builtin.apt:
    name:
      - mariadb-server
      - python3-pymysql
      - git
      - ufw 
    state: present
    update_cache: true

- name: Asegurar que MariaDB esté iniciado
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Instalar Git
  ansible.builtin.apt:
    name: git
    state: present

- name: Descargar aplicación
  ansible.builtin.git:
    repo: "{{ app_repo }}"
    dest: /opt/dbappphp
    version: main

- name: Configurar MariaDB para aceptar conexiones de red
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = {{ db_bind_address }}'
  notify: Reiniciar MariaDB

- name: Crear base de datos
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Crear usuario de la aplicación
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    host: "{{ db_allowed_host }}"
    priv: "{{ db_name }}.*:ALL"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Copiar SQL de la aplicación
  ansible.builtin.copy:
    src: /opt/dbappphp/cumpleanios.sql
    dest: /tmp/cumpleanios.sql
    remote_src: true
    owner: root
    group: root
    mode: "0600"

- name: Corregir sintaxis del SQL
  ansible.builtin.lineinfile:
    path: /tmp/cumpleanios.sql
    regexp: '^DROP DATABASE cumples IF EXISTS;'
    line: 'DROP DATABASE IF EXISTS cumples;'

- name: Importar base de datos y datos iniciales
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: import
    target: /tmp/cumpleanios.sql
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Permitir SSH (Desde el controlador)
  community.general.ufw:
    rule: allow
    port: "22"
    proto: tcp
    from_ip: "{{ controller_ip }}"

- name: Permitir MariaDB desde el servidor de aplicación
  community.general.ufw:
    rule: allow
    port: "3306"
    proto: tcp
    from_ip: "{{ db_allowed_host }}"

- name: Activar UFW
  community.general.ufw:
    state: enabled
